apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traction-ingress
  labels:
    app: traction
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
spec:
  ingressClassName: nginx
  rules:
    - host: "traction.digicred.services"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-release-traction-tenant-ui
                port:
                  number: 8080
    - host: "acapy-traction.digicred.services"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-release-traction-acapy
                port:
                  number: 8030
    - host: "admin-traction.digicred.services"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-release-traction-acapy
                port:
                  number: 8031
    - host: "proxy-traction.digicred.services"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-release-traction-tenant-proxy
                port:
                  number: 8032
