multitenant_provider:
  manager:
    class_name: "multitenant_provider.v1_0.manager.AskarMultitokenMultitenantManager"
    always_check_provided_wallet_key: true
  errors:
    on_unneeded_wallet_key: false
  token_expiry:
    units: months
    amount: 3

traction_innkeeper:
  innkeeper_wallet:
    tenant_id: innkeeper
    wallet_name: traction_innkeeper
    wallet_key: change-me
    print_key: true
    print_token: true
    connect_to_endorser:
      [
        { "endorser_alias": "digicred-endorser", "ledger_id": "digicred" },
        { "endorser_alias": "digicred-endorser-1", "ledger_id": "digicred-1" },
      ]
    create_public_did: ["digicred", "digicred-1"]
  reservation:
    auto_approve: true
    expiry_minutes: 2880
    auto_issuer: true

basicmessage_storage:
  wallet_enabled: true
